### ISSUE TITLE
Too many connections for list to show

### ISSUE THREAD

**Issue by Dalewn** [DellAquila/PowerControlRoom#1]
First of all, I really like the mod you created! It resolved so many problems with power management, I don't want to play without it anymore!

### Describe the bug
When you reach a certain amount of wireless connections, the list will become too long to display all items in a single box.
While this is probably not an issue for many, it would be nice to create/manage more connections.

### To Reproduce
Create more than 13 connections to access. The 14th connection will disappear from the selection menu.
(This might depend on the resolution you play on. Mine was 1920x1080)

### Expected behavior
It should be possible to see/select all connections in the option box.

### Screenshots
![Screenshot 2021-02-11 103154](https://user-images.githubusercontent.com/43420891/107620132-85a27000-6c54-11eb-9db5-915b2c229ad0.jpg)

### Comments
I like to create separate power plants by purpose (e.g. for steel production only), which is why I ran into this.
In my opinion the described behaviour could be fixed by either:
- making the box scrollable
- or decreasing the spacing between the connections
- or decreasing the font size

Thanks in advance!

**Comment by DellAquila** [comment]
Hi Dalewn!!! Thank you very much for that info, im really glad you like the mod! :D I made a mistake in the scrollbar (it was fixed bar in the right) on the wireless and the central pole!! 

Soon i will redo all the widgets to be good looking :) 

Im fixing now, and will update the mod asap.

**Comment by Dalewn** [comment]
Hey, thanks for the quick reply! That is great to hear!
If there is any help I can provide, feel free to ask; Although I'm more of a Java programmer...

**Comment by Dalewn** [comment]
Hey, I don't mean to sound rude but do you have an ETA for when a fix will be coming? Thanks again! :)

**Comment by DellAquila** [comment]
Hi... its on since that day.... did you have the last version of the mod?

**Comment by Dalewn** [comment]
Yes, you are absolutely right! I missed checking in SMM since I was looking for a code update here.
While the UI isn't particularly nice, it now works! 
Great job!
